# Generated by Django 3.2.5 on 2021-07-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=78)),
                ('message', models.TextField(max_length=255)),
                ('email_from', models.EmailField(default=None, max_length=254)),
                ('timeout', models.PositiveSmallIntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, 'delivering'), (1, 'delivered'), (3, 'error')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_to', to='core.emailsend')),
            ],
        ),
    ]
