# Generated by Django 3.2.4 on 2021-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsend',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'delivering'), (1, 'delivered'), (3, 'error')], default=0),
        ),
    ]
